Repository MSB-s-Projects/Generate-QR-code, pull requests merged in 2023-03, with the labels that each got.

#26 added correct link to access the web application
  README.md
Labels: bug, pwoc, easy

#22 Selector and label changing dynamically for easy handling
  views/index.ejs
Labels: enhancement, pwoc, hard

#31 Improved UI of the website
  views/index.ejs
  views/qrcode.ejs
Labels: enhancement, pwoc, hard

#35 Integrate Backend and Frontend
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .gitignore
  README.md
  app.js
  bin/www.js
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
  package.json
  pnpm-lock.yaml
  routes/index.js
  routes/users.js
  vercel.json
  views/image.ejs
  views/index.ejs
Labels: enhancement, pwoc, hard

#36 Added footer to the website
  views/index.ejs
  views/partials/footer.ejs
  views/qrcode.ejs
Labels: enhancement, pwoc, easy

#38 v2 of the app
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .gitignore
  README.md
  app.js
  bin/www.js
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
  package.json
  pnpm-lock.yaml
  routes/index.js
  routes/users.js
  vercel.json
  views/image.ejs
  views/index.ejs
Labels: enhancement, pwoc, hard

#40 [BUG]: made the website deploy ready on vercel
  vercel.json
Labels: bug, pwoc, medium
